export const CHOOSE_COUNTRY = 'CHOOSE_COUNTRY'
export const GET_COUNTRIES = 'GET_COUNTRIES'
export const SET_ALL_VIDEOS = 'SET_ALL_VIDEOS'
export const UPDATE_INDIVIDUAL_VIDEO = 'UPDATE_INDIVIDUAL_VIDEO'
